name: "Unit Tests"

on:
  push:
    branches:
      - latest
  pull_request:
    branches:
      - latest

jobs:
  test:
    runs-on: ubuntu-latest

    name: Go unit tests
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

    - name: Install libxml2-utils for xmllint
      run: sudo apt-get install libxml2-utils

    - name: Setup go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: ./go.mod

    - name: Set up gotestfmt
      uses: gotesttools/gotestfmt-action@8b4478c7019be847373babde9300210e7de34bfb # v2.2.0

    - run: make unittest
      env:
        EXTRA_TEST_FLAGS: -covermode=atomic -coverprofile=coverage.out

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab # v4.1.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
