name: "Unit Tests"

on:
  push:
    branches:
      - latest
  pull_request:
    branches:
      - latest

jobs:
  test:
    runs-on: ubuntu-latest

    name: Go unit tests
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Install libxml2-utils for xmllint
      run: sudo apt-get install libxml2-utils

    - name: Setup go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: ./go.mod

    - name: Set up gotestfmt
      uses: gotesttools/gotestfmt-action@65f1d2228f06cc5e828b84597440fbd063d12ea2 # v2.1.0

    - run: make unittest
      env:
        EXTRA_TEST_FLAGS: -covermode=atomic -coverprofile=coverage.out

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
