name: "Unit Tests"

on:
  push:
    branches:
      - latest
  pull_request:
    branches:
      - latest

jobs:
  test:
    runs-on: ubuntu-latest

    name: Go unit tests
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

    - name: Setup go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version-file: ./go.mod

    - name: Set up gotestfmt
      uses: gotesttools/gotestfmt-action@65f1d2228f06cc5e828b84597440fbd063d12ea2 # v2.1.0

    - run: make unittest
      env:
        EXTRA_TEST_FLAGS: -covermode=atomic -coverprofile=coverage.out

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
